---
- hosts: all
  vars:
    http_port: 22
    max_clients: 200
  remote_user: root
  tasks:

  - name: Add docker-ce repo
    yum_repository:
      name: docker-ce
      description: docker-ce YUM repository
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install docker
    yum:
      name: "{{ packages }}"
    vars:
      packages:
       - yum-utils
       - device-mapper-persisten-data
       - lvm2
       - docker-ce
