---
- hosts: all
  vars:
    http_port: 22
    max_clients: 200
  remote_user: root
  tasks:

  - name: Add kubernetes repo
    shell: cat <<EOF > /etc/yum.repos.d/kubernetes.repo [kubernetes] name=Kubernetes baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 enabled=1 gpgcheck=1 repo_gpgcheck=1 gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg EOF
  - name: Install Kubernetes binaries
    yum:
      name: "{{ packages }}"
    vars:
      packages:
       - kubectl
       - kubeadm
